default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: safedime_development
  username: chris
  password: password

test:
  <<: *default
  database: safedime_test
  username: chris
  password: password

production:
  <<: *default
  database: safedime_production
  username: safedime
  password: <%= ENV["SAFEDIME_DATABASE_PASSWORD"] %>
